### ISSUE TITLE
Change request to enable Land Animals to walk on land.

### ISSUE THREAD

**Issue by BartelBe** [SatyrFarm/SatyrFarm#15]
**Is your feature request related to a problem? Please describe.**
On GROUNDlevel, animals should be able to move up hills and down slopes (and should remain to walk straight on a PRIM surface when required, e.g. on skyboxes).

**Describe the solution you'd like**
- add a config line "SURFACE" = ground OR "SURFACE" = prim 
in animal.lsl (and animal-api.lsl) change 
line 630 [in the timer() section]
find "v.z = cp.z; "
replace with "
     if (SURFACE = ground)
     {v.z = llGround( ZERO_VECTOR );
      cp.z= llGround( ZERO_VECTOR );}
    else
  v.z = cp.z; 
"
and  add the SURFACE option to the setConfig(string str) options list
Additionally, you might also want to update the follower.

**Describe alternatives you've considered**
the alternative is having land animals floating in the air, when they encounter land levels that are not completely flat.

**Additional context**
just try it out and be happy

**Comment by uriesk** [comment]
Thank you.
I added it as an option a88ce66e0cc303de4f47e86ed946d9a122b63d87 that the user can enable in the menu. It's per default off, because it would break animals in skyboxes. I didn't add it to the config notecard, because the user is not supposed to have to change it, it should be written by the person who makes the animal imho.
Works fine for me.

I leave this issue open, because its still not perfect, i.e. we could use something like a max-slope that the animal can climb, so that it doesn't go up cliffs or collision detection for fences / walls.

**Comment by llaxton** [comment]
Hello, I am once again testing SF. I have the latest release from the OSG region. I came to the github and see some activity after the 11/30 date shown on the box from the OSG region. I did not notice an option to have animals follow the terrain. Which has the latest code? I do find a few issues to be reported but I want to be sure I report to whomever is handling the latest coding.

**Comment by IAmNolanPerry** [comment]
@llaxton , The Current Code in the SF Repository may not reference the latest release inworld, please ping Cody Cooper in the SF/OpenSimWorld Discord Server if you have any further questions
