### ISSUE TITLE
Newly created animals disappear on grid/region restarts

### ISSUE THREAD

**Issue by BrinleyTaliesin** [SatyrFarm/SatyrFarm#16]
**Describe the bug**
When creating new "baby" animals all is fine until the grid or region is restarted, and then they all disappear. This does not occur with unhatched rezzed eggs, but after the eggs hatch and the region restarts the newly hatched animals are gone too.

**To Reproduce**
1. Rez out any non-egg animal.
2. Restart the region.
3. All new animals will now be gone.

**Expected behavior**
I expect them to stay there :)

**Enviroment (please complete the following information):**
- OpenSimVersion : Tested on FR_Server_NY 0.9.1.1 Snail Release, FR_Server_VT 0.9.1.1 Snail Release, FR_Server_SF 0.9.0.1 Release 
- Viewer and Version : Firestorm 6.0.2 (56680) Feb  9 2019 10:23:10 (64bit) (Firestorm-Releasex64) with OpenSimulator support
- Satyr Farm Version : SatyrFarm Package v.2018.11.30, SatyrFarm Package v.2018.11.31, SF Animal Rezzer HUD - Quintonia-V3.6 

**Additional context**
Cnayl of Quintonia Farm had this to say: "All I've found so far is that it seems to be a time related thing i.e. the region restart resets egg based animals to eggs and others to a time before they were born if the animals were not that old...I have found that leaving a region up for just a couple of days seems enough to make it 'restart proof'."
Note: We have had our new animals out for 2-3 days but no longer, as the grid we are on keeps getting restarted, so unable to test this yet.

Our gridmaster said in his region console the animals are "constantly throwing red errors (bad) related to storage in the database." I am pasting the output from his region console: 
regionUUID)
   at OpenSim.Region.Framework.Scenes.SceneObjectGroup.ProcessBackup(ISimulationDataService datastore, Boolean forcedBackup)
[REGION DB]: MySQL error in ExecuteNonQuery: Incorrect string value: '\xE2\x99\x82\x0A0 ...' for column 'Text' at row 1
15:53:31 - [SCENE]: Storing of SF Cow, a09d1f0b-b909-4cb8-8dd7-20efc74d0092 in Taliesborn Farms failed with exception Incorrect string value: '\xE2\x99\x82\x0A0 ...' for column 'Text' at row 1   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at OpenSim.Data.MySQL.MySQLSimulationData.ExecuteNonQuery(MySqlCommand c)
   at OpenSim.Data.MySQL.MySQLSimulationData.StoreObject(SceneObjectGroup obj, UUID regionUUID)
   at OpenSim.Services.SimulationService.SimulationDataService.StoreObject(SceneObjectGroup obj, UUID

His comments: "Notice it is associated with storing SF Cow. This seems to tie out with the comment that the animals get reset to a time before they were born as it seems they are really never actually being stored in the database because of the SQL error. Just to be certain, I have checked the OSSL permission required to operate the Satyr Farm scripts shown here: https://opensimworld.com/farm/12 and I can confirm they are all correctly set for you."

**Comment by IAmNolanPerry** [comment]
@BrinleyTaliesin  Can you ask your Gridmaster what MySQL Server Version he uses?

**Comment by IAmNolanPerry** [comment]
@BrinleyTaliesin  Can you ask your gridmaster what MySQL Server Version he is Using?

**Comment by BrinleyTaliesin** [comment]
Funny you should ask, my gridmaster had left me an IM I just got: "My only thought is that there have been table updates to the SQL database in 0.9.1.1 which are incompatible with the Satyr Farm code as it currently exists." So there we go :)

**Comment by KassiDash** [comment]
Heyya, this is Brinley's tech guy, Kassi. 

The question asked was what database we use. We currently use MySQL 5.7. The version of Opensim we are using is 0.9.1.1 Release, which is where Brinley got confused. We are in a Windows 2016 server core ,/ .NET 4.6 environment and Brinley's region is the sole region on the simulator instance.  I hope this helps. I am able to act upon suggestions that don't impact the grid as a whole. I did try attaching an Opensim 0.9.0.1 Release simulator and restoring an OAR of Brinley's region to it, but to no avail. 

Thanks for the support, 
Kassi.

**Comment by IAmNolanPerry** [comment]
@KassiDash I don't know why It happend with MySQL 5.7, It is confirmed that it didn't work due to a change that occured with MySQL 5.8.x, Please See Here([Link To OpenSimulator Mantis Bug](http://opensimulator.org/mantis/view.php?id=8392))

**Comment by KassiDash** [comment]
Oh dear and that is all back in 2018 with no real resolution. My residents will be very disappointed I'm sure. I will check the minor release of our MySQL installation. 

Out of interest, has this only ever been reported on Windows/MySQL installations? Have there been reports on Linux/MySQL installations?

Thanks,
Kassi.

**Comment by IAmNolanPerry** [comment]
I am not entirely sure, I ran a server back then on Windows through AWS and through a OpenSimWorld Private Server we have running Ubuntu, and It had the same issue on both, so I assume it had the problem on both.

**Comment by KassiDash** [comment]
So, I'm going to try something, but I won't implement it on my grid until I'm absolutely sure it is the issue. Please check out this post:

https://mathiasbynens.be/notes/mysql-utf8mb4

As you can see, there is an issue with UFT-8 being properly supported in MySQL of all flavours and the cure is to update collations and character sets to utf8mb4, which has been available since MySQL 5.5.3 and addresses the issue of storing high ASCII characters. Now, utf8mb4 is fully backwards compatible with utf-8 I am told in this article, but I have a grid to support and so will verify that for myself. 

Would appreciate feedback from any who suffer this issue as to the character-set/collation on their assets table, which I am assuming is the table being hit by this insert/update, please correct me if this is not the case.

I'm probably chasing a red herring, but it's worth a try I think.
Kassi.

**Comment by Outworldz** [comment]
Nice find.  But probably not it.   The character it is complaining about is an umbrella, which is in UTF-8

From https://www.utf8-chartable.de/unicode-utf8-table.pl?start=9728&number=128&names=-&utf8=string-literal

U+2602 | ☂ | \xe2\x98\x82  

Is your database already set for UTF-8?  If not, a fix would be much simpler - just make sure the database is using utf-8.

[mysqld]
character-set-server=utf8

 I use the above in all Dreamgrid.  Looks like I need to change it to match your find to stay woth UTF-8, at least.  Core would have to address the vulnerabilities and changes to the main schema, which I bet they will be very reluctant to do. 

Possible changes to my.ini

[client]
port=3306
default-character-set = utf8

[mysql]
default-character-set = utf8

[mysqld]
character-set-server=utf8
character-set-client-handshake = FALSE
collation-server = utf8

Also, be sure you are using  this in [mysqld]
# required for large mesh files
max_allowed_packet=64M

**Comment by Outworldz** [comment]
Anothert possible fix is to switch to FSAssets, a file based asset table.

**Comment by IAmNolanPerry** [comment]
@Outworldz Thank you for your help, however I also must ask that you refrain from using Vulgar/Inappropriate Words within the SatyrFarm Projects.

**Comment by Outworldz** [comment]
DreamGrid uses Myssql Version 5.5.8 ( from select Version();) .

5.58 does not support the **collation-server = utf8** line.  

I settled on this for the server:
```

[client]
port=3306
default-character-set = utf8

[mysql]
default-character-set = utf8

mysqld]
character-set-server=utf8
character-set-client-handshake = FALSE
lower_case_table_names = 1

```

**Comment by KassiDash** [comment]
Hey Outworldz, thanks for the insight. My databases are all set to utf-8, so that does not seem to be a deficiency in my case. 

I understand the umbrella is in utf-8 as the standard is written and as your link above indicates. The problem though is that utf-8, as implemented in MySQL, does not support the full utf-8 character set, which was the purpose behind utf8mb4, i.e. to fix that issue. The part of Mathias' blog that tweaked my interest being:

"In fact, MySQL’s utf8 only allows you to store 5.88% ((0x00FFFF + 1) / (0x10FFFF + 1)) of all possible Unicode code points. Proper UTF-8 can encode 100% of all Unicode code points."

I will continue to implement my test in the hope that it resolves the issue for my grid population.

Cheers!
Kofi.

**Comment by opensimworld** [comment]
I don't know if it helps, but this is an old error related to utf8 encoding settings in mysql: https://forums.osgrid.org/viewtopic.php?f=14&t=4709&start=0

Satyrfarm only uses 2 UTF8 characters (the male and female symbols) which do not require utf8mb4 afaik. (Unless of course you have added an umbrella  to your animal names) 

I wonder if opensimulator is using a different encoding to connect to the mysql server which causes the incompatibility. Is there a way to specify the encoding in the mysql connection string in opensimulator?

**Comment by KassiDash** [comment]
It is indeed strange, but there was no resolution in that link either. I could try adding this to my connection string:

CharSet=utf8;

but I'm unsure of the consequences elsewhere.

**Comment by Outworldz** [comment]
Adding a CharSet=utf8 to the connection string only affects sending of data to Mysql, it does not affect returned data.  That may be an issue, but worth a try.

Try this test program before and after adding the UTF-8 connection data to the My.ini file and restarting MySQL.  This test works with mysql 5.5.8 with just 
```
[mysql]
default-character-set = utf8

```
This script may or may not show the problem  for you.   I get no errors and it saves and prints the UTF-8.

```
default
{
    state_entry()
    {
        llSay(0, "★♀♁♂☂★");
    }
}
```

**Comment by punyauk** [comment]
Turning the hover text off (as that contains the male and female symbols) enabled the newly created animals to be stored. They turned off text, restarted region and animals are still there. Then they turned back on hovertext and tried another restart and the animals again come back, so presumably when the the text is off they store okay.  Going forward I'm releasing an update to the animal script with multilingual support so it will be easy enough to switch to non-unicode characters. Not actually fixing the problem but a work around until a solution is given

**Comment by sarapayne** [comment]
Linked to  my new [Opensimulator Mantis Report](http://opensimulator.org/mantis/view.php?id=8707)

This issue is going to become much bigger for you in the near future I fear. I came across this when moving customers to a new server. My new server is running Ubuntu 20.04 with MySql8. I have tried creating databases with the following:

- CREATE DATABASE mydatabase CHARACTER SET utf8mb3
- CREATE DATABASE mydatabase CHARACTER SET utf8mb3 COLLATE utf8_general_ci;
- CREATE DATABASE mydatabase CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci;

- **mb4 was done as a test since the error string looks like it should be mb4
- CREATE DATABASE mydatabase CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

All of the above generate the same results in the console. 

`2020-05-24 09:06:30,653 ERROR [REGION DB]: MySQL error in ExecuteNonQuery: Incorrect string value: '\xE2\x99\x80\x0A0 ...' for column 'Text' at row 1
2020-05-24 09:06:30,656 ERROR [SCENE]: Storing of SF Elephant, dc5e01a2-6acd-4a63-8831-c6089855220e in Testing-0920-256 failed with exception Incorrect string value: '\xE2\x99\x80\x0A0 ...' for column 'Text' at row 1 at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00096] in <0004ab8b375b422f9000ac25a68089d9>:0
  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int64& insertedId) [0x00026] in <0004ab8b375b422f9000ac25a68089d9>:0
  at MySql.Data.MySqlClient.Driver.GetResult (System.Int32 statementId, System.Int32& affectedRows, System.Int64& insertedId) [0x00000] in <0004ab8b375b422f9000ac25a68089d9>:0
  at MySql.Data.MySqlClient.Driver.NextResult (System.Int32 statementId, System.Boolean force) [0x00023] in <0004ab8b375b422f9000ac25a68089d9>:0
  at MySql.Data.MySqlClient.MySqlDataReader.NextResult () [0x00205] in <0004ab8b375b422f9000ac25a68089d9>:0
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00315] in <0004ab8b375b422f9000ac25a68089d9>:0
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader () [0x00000] in <0004ab8b375b422f9000ac25a68089d9>:0
  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00033] in <0004ab8b375b422f9000ac25a68089d9>:0
  at OpenSim.Data.MySQL.MySQLSimulationData.ExecuteNonQuery (MySql.Data.MySqlClient.MySqlCommand c) [0x00024] in <44a4f7ec66f548ab8c3c1e4870853388>:0
  at OpenSim.Data.MySQL.MySQLSimulationData.StoreObject (OpenSim.Region.Framework.Scenes.SceneObjectGroup obj, OpenMetaverse.UUID regionUUID) [0x00078] in <44a4f7ec66f548ab8c3c1e4870853388>:0
  at OpenSim.Services.SimulationService.SimulationDataService.StoreObject (OpenSim.Region.Framework.Scenes.SceneObjectGroup obj, OpenMetaverse.UUID regionUUID) [0x00000] in <8e9d48cb71f0426294098b5529543b2f>:0
  at OpenSim.Region.Framework.Scenes.SceneObjectGroup.ProcessBackup (OpenSim.Region.Framework.Interfaces.ISimulationDataService datastore, System.Boolean forcedBackup) [0x00341] in <3614d381280e4d09950777f021d0c4bf>:0`

As was originally stated the error prevents the animals being saved in the database. Resulting in Oar restores reverting the animals to babies. When the simulator is restarted all the animals vanish. To make sure this wasn't caused by an old version I went and picked up a new copy of the farm system to test with today. 

Reproduction Steps:
1. Load a simulator on a database created with MySql8 using any of the methods shown above. 
2. Rez any animal out of the rez box with no changes
3. Restart the simulator and watch the errors (one per animal). 
4. Log back and try to find your animals (you won't, they won't be there)

MySql5 is no longer shipped with most current Linux distributions. They actually consider UT8mb3 as deprecated, marked for future removal. According to Ubit MariaDB does not show the error for the farm system at the moment, but the advice is to avoid special characters of any kind since similar issues have been reported on Maria and that was their advice.  

About the FSASSET suggestion. That might work if the option to use MySQL as a fall back is not set. Using FSASSET's with the fallback option enabled still causes the problems (how my grid is setup).

**Comment by punyauk** [comment]
the newer animal script now allows you to set male and female as some non-unicode character.  I am using a mariaDB/Ubuntu 20 server though and confirm it works okay with the unicode symbols.

**Comment by sarapayne** [comment]
It might allow you to do that, but most people will not look at stuff like this. Surely it would make sense to have the defaults set to not use any special characters? Anyway it's your product, but using the default out of the box settings the animals simply do not work correctly on the newer version of MySql

**Comment by punyauk** [comment]
Do characters such as ê etc work okay as if not then that makes it a bigger issue for supporting multi-language, which is something I have added recently.

**Comment by sarapayne** [comment]
I honestly do not know for certain, however, based on all the reading I did while trying figure out why I had scrolling terminal errors I strongly suspect the answer to that question is no. There were many bits of software giving similar errors. Most of them using characters like the one you just used. Displaying those in MySQL 8 requires using mb4 rather than mb3. There is quite a lot on stack exchange if you Google the error shown in my first comment.

**Comment by punyauk** [comment]
I'm releasing an new edition of my version of the SatyrFarm system soon , so will take that on board and set non-unicode as the standard with notes on why it's done and how people can change back to the 'prettier' version :)

**Comment by sarapayne** [comment]
Re MariaDB
mysql  Ver 15.1 Distrib 10.3.22-MariaDB 
CREATE DATABASE mydatabase CHARACTER SET utf8mb3
CREATE DATABASE mydatabase CHARACTER SET utf8mb3 COLLATE utf8_general_ci;

Both of these have given me the same results as MySql8. 
MySQL error in ExecuteNonQuery: Incorrect string value: '\xE2\x99\x80\x0A0 ...' for column `SimulatorTesting0920`.`prims`.`Text` at row 1

Tampa on the Opensimulator mantis is using MariaDB 10.1. This means the current versions of both MySql and MariaDB when used with opensim will not handle these special characters. 

The worst part is when the database errors they occur, due to a memory leak, around 20 items will increase server memory use by around 15gb in just 24h.

**Comment by opensimworld** [comment]
Since this seems to be a recurring issue, and don't want to confuse users with the internals of MySQL, i went ahead and changed the animal.lsl script to display [M] or [F] instead of the male/female symbols (those are the only unicode characrters used in the farm

**Comment by sarapayne** [comment]
Tested and confirmed as resolved, all animals now remain on the region after a restart and there are no scrolling errors in the console.

**Comment by sarapayne** [comment]
Question, my resident tells me that when she goes to update her items with the latest it tells her they are up to date, yet the items still cause the same issues as before. I tested freshly rezzed items. When the update happens,  do some of the old characters get left behind? Or is she not doing the update correctly?

**Comment by BrinleyTaliesin** [comment]
If I understand opensimworld, he updated the script here, I'm not sure he updated the script in the animal rezzer and Satyr package? And if he did, I don't know that the animal version was changed, just the script, so the rezzer might not see anything as needing an update.  With the Quintonia edition, there's this in the config file of the rezzer: set VER to -1 to force update but note that versions before 4.1 can't be upgraded and must be replaced)
VER=-1
But the basic Satyr version does not have that option. I'd say start with newly rezzed animals. Or try the Quintionia edition hehe.

**Comment by manwapastorelli** [comment]
That sounds like the answer. Freshly rezzed items do work (i tested that myself). But my resident is getting a message saying her animals are up to date. So the items already rezzed will break if moved to a newer database version. Is it possible to get the animal version changed so when people update existing items older setups can be migrated to newer ones. Currently i am running an entire server just for one customer with farm stuff out. Everything else is now on the newer and substantially quicker MySql8.
